version: '3.8'

services:
  leaderboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-in-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      # Persist database
      - leaderboard-data:/app/server/database
      # Persist logs
      - leaderboard-logs:/app/logs
    restart: unless-stopped
    networks:
      - leaderboard-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session storage (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: leaderboard-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - leaderboard-network
  #   command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: leaderboard-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - leaderboard-app
  #   restart: unless-stopped
  #   networks:
  #     - leaderboard-network

volumes:
  leaderboard-data:
    driver: local
  leaderboard-logs:
    driver: local
  # redis-data:
  #   driver: local

networks:
  leaderboard-network:
    driver: bridge