name: Deploy Leaderboard

on:
  # Stabalize when the workflow is stable
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "hackathon/leaderboard/**"
  pull_request:
    branches: [main]
    paths:
      - "hackathon/leaderboard/**"

concurrency: workflow

permissions:
  id-token: write 
  contents: read 

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  TF_VAR_postgresql_admin_username: ${{ secrets.POSTGRES_LOGIN_USER }}
  TF_VAR_postgresql_admin_password: ${{ secrets.POSTGRES_LOGIN_PWD }}
  
defaults:
  run:
    working-directory: ./hackathon/leaderboard/terraform
jobs:
  deploy:
    name: Run OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Check Tofu formatting
        run: |
          tofu fmt -check -recursive

      - name: Create Tofu plan
        run: |
          tofu init
          tofu validate
          tofu plan

      - name: Show Tofu plan
        run: |
          tofu show
          
      - name: Run Tofu apply
        run: |
          tofu apply -auto-approve