name: Build and Push Leaderboard Images to ACR

on:
  # Stabalize when the workflow is stable
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "hackathon/leaderboard/**"
      - "!hackathon/leaderboard/terraform/**"

  pull_request:
    branches: [main]
    paths:
      - "hackathon/leaderboard/**"
      - "!hackathon/leaderboard/terraform/**"

concurrency: workflow

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Azure Registry Get Login"
        uses: azure/CLI@v2
        with:
          inlineScript: |
            ACR_TOKEN=$(az acr login --name ${{ secrets.ACR_LOGIN_SERVER }} --expose-token --query accessToken --output tsv)
            echo "ACR_TOKEN=$ACR_TOKEN" >> $GITHUB_ENV

      - name: Log in to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ env.ACR_TOKEN }}

      - name: Copy goals.json to leaderboard directory
        run: |
          cp hackathon/goals.json hackathon/leaderboard/goals.json

      - name: Build Docker images
        run: |
          cd hackathon/leaderboard
          docker build -f Dockerfile.production -t ${{ secrets.ACR_LOGIN_SERVER }}/leaderboard:latest .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/leaderboard:latest
